/* Each question is a molecular graph plus explicit electron-pair transfers.
   Product bond orders, lone pairs and formal charges are derived from those transfers. */
const QUESTION_BANK=[];
const clone=x=>JSON.parse(JSON.stringify(x));
const keyBond=(a,b)=>[a,b].sort().join('~');
function graph(){return{atoms:[],bonds:[]}}
function atom(g,id,element,x,y,h=0,lp=0,label){g.atoms.push({id,element,x,y,h,lp,label:label||element+(h?'H'+(h>1?h:''):'')});return id}
function group(g,id,label,x,y){g.atoms.push({id,element:'R',x,y,h:0,lp:0,label});return id}
function bond(g,a,b,order=1){g.bonds.push({a,b,order});}
const LP=id=>({type:'lp',id});const BD=(a,b)=>({type:'bond',a,b});
const move=(from,to)=>({from,to});
function formal(g,a){if(a.element==='R')return 0;const v={H:1,C:4,N:5,O:6,F:7,Cl:7,Br:7,I:7}[a.element];return v-2*a.lp-a.h-g.bonds.filter(b=>b.a===a.id||b.b===a.id).reduce((s,b)=>s+b.order,0)}
function apply(g,moves){const p=clone(g);function change(loc,n){if(loc.type==='lp'){p.atoms.find(a=>a.id===loc.id).lp+=n;return}let b=p.bonds.find(b=>keyBond(b.a,b.b)===keyBond(loc.a,loc.b));if(!b){b={a:loc.a,b:loc.b,order:0};p.bonds.push(b)}b.order+=n}for(const m of moves){change(m.from,-1);change(m.to,1)}p.bonds=p.bonds.filter(b=>b.order>0);return p}
function addRes(title,level,g,moves,reverse=false,family=''){const product=apply(g,moves);QUESTION_BANK.push({id:'r'+String(QUESTION_BANK.filter(q=>q.topic==='resonance').length+1).padStart(3,'0'),topic:'resonance',level,title: title+(reverse?' · reverse contributor':''),family,start:reverse?product:g,product:reverse?g:product,moves:reverse?moves.map(m=>move(m.to,m.from)):moves,context:'Draw every curly arrow needed to convert resonance structure A into resonance structure B.',explanation:'The atom positions and total charge stay the same. These drawings are contributors to one resonance hybrid; their contributions need not be equal.'})}
const SUBS=[['H','H'],['CH3','methyl'],['CH2CH3','ethyl'],['CH(CH3)2','isopropyl'],['C6H5','phenyl']];
function attach(g,id,label,center,x,y){if(label==='H')atom(g,id,'H',x,y);else group(g,id,label,x,y);bond(g,center,id)}
// EASY: 20 carbonyl, 10 imine and 5 allylic-cation questions; one arrow each.
const carbonyls=[['H','H','Formaldehyde'],['CH3','H','Acetaldehyde'],['CH2CH3','H','Propanal'],['CH2CH2CH3','H','Butanal'],['CH(CH3)2','H','2-Methylpropanal'],['C6H5','H','Benzaldehyde'],['CH3','CH3','Acetone'],['CH3','CH2CH3','2-Butanone'],['CH2CH3','CH2CH3','3-Pentanone'],['C6H5','CH3','Acetophenone']];
for(const [r1,r2,name]of carbonyls){const g=graph();atom(g,'c','C',260,190);atom(g,'o','O',390,190,0,2);bond(g,'c','o',2);attach(g,'r1',r1,'c',195,78);attach(g,'r2',r2,'c',195,302);for(const rev of [false,true])addRes(name,'easy',g,[move(BD('c','o'),LP('o'))],rev,'Carbonyl polarization')}
for(const [r,name]of SUBS){const g=graph();atom(g,'c','C',220,190,1);atom(g,'n','N',355,190,0,1);atom(g,'h','H',425,130);bond(g,'c','n',2);bond(g,'n','h');attach(g,'r',r,'c',120,130);for(const rev of [false,true])addRes((r==='H'?'Methanimine':name+'-substituted imine'),'easy',g,[move(BD('c','n'),LP('n'))],rev,'Imine polarization')}
for(const [r,name]of SUBS){const g=graph();atom(g,'a','C',145,200,2);atom(g,'b','C',270,135,1);atom(g,'c','C',395,200,1);bond(g,'a','b',2);bond(g,'b','c');attach(g,'r',r,'c',485,145);addRes((r==='H'?'Allyl cation':name+'-substituted allyl cation'),'easy',g,[move(BD('a','b'),BD('b','c'))],false,'Allylic cation')}
// MODERATE: two coupled arrows; amides, carboxylates, enolates, allylic anions.
for(const [r,name]of SUBS){const g=graph();atom(g,'c','C',280,190);atom(g,'o','O',360,85,0,2);atom(g,'n','N',390,270,2,1);bond(g,'c','o',2);bond(g,'c','n');attach(g,'r',r,'c',150,190);for(const rev of [false,true])addRes((r==='H'?'Formamide':name+' carboxamide'),'moderate',g,[move(LP('n'),BD('n','c')),move(BD('c','o'),LP('o'))],rev,'Amide donation')}
for(const [r,name]of SUBS){const g=graph();atom(g,'c','C',270,190);atom(g,'o1','O',340,70,0,2);atom(g,'o2','O',340,310,0,3);bond(g,'c','o1',2);bond(g,'c','o2');attach(g,'r',r,'c',125,190);for(const rev of [false,true])addRes((r==='H'?'Formate':r==='CH3'?'Acetate':name+' carboxylate'),'moderate',g,[move(LP('o2'),BD('o2','c')),move(BD('c','o1'),LP('o1'))],rev,'Carboxylate resonance')}
for(const [r,name]of SUBS){const g=graph();atom(g,'a','C',165,225,2,1);atom(g,'c','C',290,155);atom(g,'o','O',290,45,0,2);bond(g,'a','c');bond(g,'c','o',2);attach(g,'r',r,'c',415,225);for(const rev of [false,true])addRes((r==='H'?'Acetaldehyde enolate':name+'-substituted enolate'),'moderate',g,[move(LP('a'),BD('a','c')),move(BD('c','o'),LP('o'))],rev,'Enolate resonance')}
for(const [r,name]of SUBS){const g=graph();atom(g,'a','C',130,215,2,1);atom(g,'b','C',260,145,1);atom(g,'c','C',390,215,1);bond(g,'a','b');bond(g,'b','c',2);attach(g,'r',r,'c',485,145);addRes((r==='H'?'Allyl anion':name+'-substituted allyl anion'),'moderate',g,[move(LP('a'),BD('a','b')),move(BD('b','c'),LP('c'))],false,'Allylic anion')}
// HARD: three coupled arrows through extended conjugation.
for(const [r,name]of SUBS){const g=graph();atom(g,'a','C',85,220,2,1);atom(g,'b','C',205,145,1);atom(g,'c','C',325,220,1);atom(g,'d','C',445,145);atom(g,'o','O',445,35,0,2);bond(g,'a','b');bond(g,'b','c',2);bond(g,'c','d');bond(g,'d','o',2);attach(g,'r',r,'d',565,220);for(const rev of [false,true])addRes(name+'-substituted dienolate','hard',g,[move(LP('a'),BD('a','b')),move(BD('b','c'),BD('c','d')),move(BD('d','o'),LP('o'))],rev,'Extended enolate resonance')}
for(const [r,name]of SUBS){const g=graph();atom(g,'n','N',90,220,2,1);atom(g,'a','C',210,145,1);atom(g,'b','C',330,220,1);atom(g,'c','C',450,145);atom(g,'o','O',450,35,0,2);bond(g,'n','a');bond(g,'a','b',2);bond(g,'b','c');bond(g,'c','o',2);attach(g,'r',r,'c',570,220);for(const rev of [false,true])addRes(name+'-substituted conjugated amino carbonyl','hard',g,[move(LP('n'),BD('n','a')),move(BD('a','b'),BD('b','c')),move(BD('c','o'),LP('o'))],rev,'Donation through conjugation')}
for(const [r,name]of SUBS){const g=graph();const pts=[[235,105],[330,160],[330,270],[235,325],[140,270],[140,160]];pts.forEach(([x,y],i)=>atom(g,'c'+i,'C',x,y,i===0?0:1));for(let i=0;i<6;i++)bond(g,'c'+i,'c'+((i+1)%6),[0,2,4].includes(i)?2:1);atom(g,'o','O',235,0,0,3);bond(g,'o','c0');if(r!=='H'){g.atoms.find(a=>a.id==='c5').h=0;g.atoms.find(a=>a.id==='c5').label='C';attach(g,'r',r,'c5',35,100)}for(const rev of [false,true])addRes((r==='H'?'Phenoxide':'2-'+name+'phenoxide')+' · para contributor','hard',g,[move(LP('o'),BD('o','c0')),move(BD('c0','c1'),BD('c1','c2')),move(BD('c2','c3'),LP('c3'))],rev,'Aromatic delocalization')}

// Replace repeated members with distinct resonance motifs while preserving 35/35/30 level counts.
const replacedResonanceIds=new Set(['r011','r012','r013','r014','r015','r016','r017','r018','r019','r020','r036','r037','r038','r039','r040','r041','r042','r043','r044','r045','r071','r072','r073','r074','r075','r076','r077','r078','r079','r080']);
for(let i=QUESTION_BANK.length-1;i>=0;i--)if(replacedResonanceIds.has(QUESTION_BANK[i].id))QUESTION_BANK.splice(i,1);
function addVariedRes(id,title,level,g,moves,reverse=false,family=''){const product=apply(g,moves);QUESTION_BANK.push({id,topic:'resonance',level,title:title+(reverse?' · reverse contributor':''),family,start:reverse?product:g,product:reverse?g:product,moves:reverse?moves.map(m=>move(m.to,m.from)):moves,context:'Draw every curly arrow needed to convert resonance structure A into resonance structure B.',explanation:'The atom positions and total charge stay the same. These drawings are contributors to one resonance hybrid; their contributions need not be equal.'})}
for(const [r,name]of [['CH3','Acetonitrile'],['CH2CH3','Propionitrile'],['C6H5','Benzonitrile']]){const g=graph();atom(g,'c','C',260,185);atom(g,'n','N',400,185,0,1);bond(g,'c','n',3);group(g,'r',r,125,185);bond(g,'r','c');for(const reverse of [false,true])addVariedRes('rv-e-nitrile-'+name.toLowerCase()+(reverse?'-reverse':''),name,'easy',g,[move(BD('c','n'),LP('n'))],reverse,'Nitrile polarization')}
for(const [alkyl,name]of [['CH3','Methoxymethyl cation'],['CH2CH3','Ethoxyethyl cation']]){const g=graph();atom(g,'c','C',265,200,2);atom(g,'o','O',390,200,0,2);bond(g,'c','o');group(g,'r',alkyl,515,130);bond(g,'o','r');if(name==='Ethoxyethyl cation'){g.atoms.find(a=>a.id==='c').h=1;group(g,'cr','CH3',135,130);bond(g,'cr','c')}for(const reverse of [false,true])addVariedRes('rv-e-oxo-'+alkyl+(reverse?'-reverse':''),name,'easy',g,[move(LP('o'),BD('o','c'))],reverse,'Lone-pair stabilization of a carbocation')}
for(const [r,name]of [['CH3','Nitromethane'],['CH2CH3','Nitroethane'],['CH(CH3)2','2-Nitropropane'],['C6H5','Nitrobenzene'],['C6H11','Nitrocyclohexane']]){const g=graph();atom(g,'n','N',285,190,0,0);atom(g,'o1','O',355,70,0,2);atom(g,'o2','O',355,310,0,3);bond(g,'n','o1',2);bond(g,'n','o2');group(g,'r',r,135,190);bond(g,'r','n');addVariedRes('rv-m-nitro-'+name.toLowerCase(),name,'moderate',g,[move(LP('o2'),BD('o2','n')),move(BD('n','o1'),LP('o1'))],false,'Nitro-group resonance')}
for(const [r,name]of SUBS){const g=graph();atom(g,'c','C',285,190);atom(g,'n1','N',405,105,1,1);atom(g,'n2','N',405,270,2,1);bond(g,'c','n1',2);bond(g,'c','n2');attach(g,'r',r,'c',135,190);addVariedRes('rv-m-amidine-'+name.replace(/\W/g,''),r==='H'?'Formamidine':'N-unsubstituted '+name+' amidine','moderate',g,[move(LP('n2'),BD('n2','c')),move(BD('c','n1'),LP('n1'))],false,'Amidine charge-separated contributor')}
for(const [r,name]of [['CH3','methyl'],['CH2CH3','ethyl'],['CH(CH3)2','isopropyl'],['C6H5','phenyl'],['C6H11','cyclohexyl']]){const g=graph(),pts=[[95,230],[205,166],[320,230],[435,166],[550,230]];pts.forEach(([x,y],i)=>atom(g,'c'+i,'C',x,y,i===0?2:i===4?1:1,i===0?1:0));bond(g,'c0','c1');bond(g,'c1','c2',2);bond(g,'c2','c3');bond(g,'c3','c4',2);group(g,'r',r,660,166);bond(g,'c4','r');addVariedRes('rv-h-pentadienyl-'+name,name+'-substituted pentadienyl anion','hard',g,[move(LP('c0'),BD('c0','c1')),move(BD('c1','c2'),BD('c2','c3')),move(BD('c3','c4'),LP('c4'))],false,'Pentadienyl anion delocalization')}
for(const [r,name]of SUBS){const g=graph(),pts=[[235,105],[330,160],[330,270],[235,325],[140,270],[140,160]];pts.forEach(([x,y],i)=>atom(g,'c'+i,'C',x,y,i===0?0:1));for(let i=0;i<6;i++)bond(g,'c'+i,'c'+((i+1)%6),[0,2,4].includes(i)?2:1);atom(g,'n','N',235,0,2,1);bond(g,'n','c0');if(r!=='H'){g.atoms.find(a=>a.id==='c5').h=0;attach(g,'r',r,'c5',35,100)}addVariedRes('rv-h-aniline-'+name.replace(/\W/g,''),(r==='H'?'Aniline':'2-'+name+'aniline')+' · para contributor','hard',g,[move(LP('n'),BD('n','c0')),move(BD('c0','c1'),BD('c1','c2')),move(BD('c2','c3'),LP('c3'))],false,'Aniline donation into the aromatic ring')}

// Five additional hard aromatic examples. Each reaches the para contributor in one complete arrow set.
function aromaticRing(){const g=graph(),pts=[[285,105],[380,160],[380,270],[285,325],[190,270],[190,160]];pts.forEach(([x,y],i)=>atom(g,'c'+i,'C',x,y,i===0?0:1));for(let i=0;i<6;i++)bond(g,'c'+i,'c'+((i+1)%6),[0,2,4].includes(i)?2:1);return g}
{
 const g=aromaticRing();atom(g,'o','O',285,0,0,2);bond(g,'o','c0');attach(g,'m','CH3','o',390,-35);
 addVariedRes('rv-h-aromatic-anisole','Anisole · para contributor','hard',g,[move(LP('o'),BD('o','c0')),move(BD('c0','c1'),BD('c1','c2')),move(BD('c2','c3'),LP('c3'))],false,'Lone-pair donation into an aromatic ring')
}
{
 const g=aromaticRing();g.atoms.find(a=>a.id==='c0').h=1;
 addVariedRes('rv-h-aromatic-benzene','Benzene · alternate Kekulé contributor','hard',g,[move(BD('c0','c1'),BD('c1','c2')),move(BD('c2','c3'),BD('c3','c4')),move(BD('c4','c5'),BD('c5','c0'))],false,'Benzene resonance');
 // Either cyclic arrow direction gives the same alternate Kekulé contributor.
 QUESTION_BANK[QUESTION_BANK.length-1].alternativeMoves=[[move(BD('c0','c1'),BD('c5','c0')),move(BD('c2','c3'),BD('c1','c2')),move(BD('c4','c5'),BD('c3','c4'))]]
}
{
 const g=aromaticRing();atom(g,'b','C',285,0,2,1);bond(g,'b','c0');
 addVariedRes('rv-h-aromatic-benzyl-anion','Benzyl anion · para contributor','hard',g,[move(LP('b'),BD('b','c0')),move(BD('c0','c1'),BD('c1','c2')),move(BD('c2','c3'),LP('c3'))],false,'Benzylic anion delocalization')
}
{
 const g=aromaticRing();atom(g,'b','C',285,0,2,0);bond(g,'b','c0');
 addVariedRes('rv-h-aromatic-benzyl-cation','Benzyl cation · para contributor','hard',g,[move(BD('c0','c1'),BD('b','c0')),move(BD('c2','c3'),BD('c1','c2'))],false,'Benzylic cation delocalization')
}
{
 const g=aromaticRing();atom(g,'n','N',285,0,0,0);atom(g,'o1','O',205,-60,0,3);atom(g,'o2','O',365,-60,0,2);bond(g,'n','c0');bond(g,'n','o1');bond(g,'n','o2',2);
 addVariedRes('rv-h-aromatic-nitrobenzene','Nitrobenzene · para contributor','hard',g,[move(BD('c0','c1'),BD('n','c0')),move(BD('c2','c3'),BD('c1','c2')),move(BD('n','o2'),LP('o2'))],false,'Electron withdrawal from an aromatic ring')
}
const reorderedResonance=[];for(const level of ['easy','moderate','hard']){const original=QUESTION_BANK.filter(q=>q.level===level&&!q.id.startsWith('rv-')),varied=QUESTION_BANK.filter(q=>q.level===level&&q.id.startsWith('rv-'));let oi=0,vi=0;while(oi<original.length||vi<varied.length){for(let n=0;n<2&&oi<original.length;n++)reorderedResonance.push(original[oi++]);if(vi<varied.length)reorderedResonance.push(varied[vi++])}}QUESTION_BANK.splice(0,QUESTION_BANK.length,...reorderedResonance);
// Acid/base building blocks. Explicit transferable H is kept separate from implicit H labels.
function basePart(type){const g=graph(),x=150,y=180;let donor='base',name,productName,hOffset={x:90,y:60};
const amines={ammonia:[3,[],'NH3','NH4+'],methylamine:[2,['CH3'],'CH3NH2','CH3NH3+'],dimethylamine:[1,['CH3','CH3'],'(CH3)2NH','(CH3)2NH2+'],trimethylamine:[0,['CH3','CH3','CH3'],'(CH3)3N','(CH3)3NH+'],amide:[2,[],'NH2−','NH3']};
if(amines[type]){const[h,rs,n,p]=amines[type],positions=rs.length===1?[[45,180]]:rs.length===2?[[90,75],[90,285]]:[[40,180],[205,85],[205,275]];atom(g,donor,'N',x,y,h,type==='amide'?2:1);rs.forEach((r,i)=>attach(g,'br'+i,r,donor,...positions[i]));if(type==='trimethylamine')hOffset={x:100,y:0};name=n;productName=p;}
else if(type==='acetate'){atom(g,'bc','C',120,180);atom(g,'bo','O',120,75,0,2);atom(g,donor,'O',230,235,0,3);group(g,'bm','CH3',35,235);bond(g,'bc','bo',2);bond(g,'bc',donor);bond(g,'bc','bm');name='CH3CO2−';productName='CH3CO2H';}
else if(type==='acetylide'){atom(g,donor,'C',195,180,0,1);atom(g,'bc','C',75,180,1);bond(g,donor,'bc',3);name='HC≡C−';productName='HC≡CH';}
else if(type==='pyridine'){const pts=[[155,180],[105,93],[5,93],[-45,180],[5,267],[105,267]];pts.forEach(([px,py],i)=>atom(g,i===0?donor:'bn'+i,i===0?'N':'C',px,py,i===0?0:1,i===0?1:0));for(let i=0;i<6;i++)bond(g,i===0?donor:'bn'+i,(i+1)%6===0?donor:'bn'+((i+1)%6),i%2===0?2:1);name='Pyridine';productName='Pyridinium';}
else {const negative=['hydroxide','methoxide','ethoxide'].includes(type),water=['water','hydroxide'].includes(type);atom(g,donor,'O',x,y,water?(negative?1:2):(negative?0:1),negative?3:2);if(!water)attach(g,'br',type==='ethanol'||type==='ethoxide'?'CH2CH3':'CH3',donor,45,120);const names={water:['H2O','H3O+'],methanol:['CH3OH','CH3OH2+'],ethanol:['CH3CH2OH','CH3CH2OH2+'],hydroxide:['HO−','H2O'],methoxide:['CH3O−','CH3OH'],ethoxide:['CH3CH2O−','CH3CH2OH']};[name,productName]=names[type];}
return{g,donor,name,productName,hOffset};}
function acidPart(type){const g=graph();let center='acid',name,productName,extra=[];const x=465,y=180;atom(g,'proton','H',350,180);
if(['HCl','HBr','HI','HF'].includes(type)){atom(g,center,type.slice(1),x,y,0,3);bond(g,'proton',center);name=type;productName=type.slice(1)+'−';}
else if(type==='methyloxonium'){atom(g,center,'O',465,180,1,1);bond(g,'proton',center);attach(g,'ar','CH3',center,565,115);name='CH3OH2+';productName='CH3OH';}
else if(type==='hydronium'){atom(g,center,'O',x,y,2,1);bond(g,'proton',center);name='H3O+';productName='H2O';}
else if(['acetic','formic','propionic'].includes(type)){atom(g,center,'O',445,180,0,2);atom(g,'ac','C',535,120);atom(g,'ao','O',535,10,0,2);bond(g,'proton',center);bond(g,center,'ac');bond(g,'ac','ao',2);attach(g,'ar',type==='acetic'?'CH3':type==='propionic'?'CH2CH3':'H','ac',630,180);name=type==='acetic'?'CH3CO2H':type==='propionic'?'CH3CH2CO2H':'HCO2H';productName=type==='acetic'?'CH3CO2−':type==='propionic'?'CH3CH2CO2−':'HCO2−';}
else if(type==='phenol'){atom(g,center,'O',455,180,0,2);bond(g,'proton',center);group(g,'ar','C6H5',555,120);bond(g,center,'ar');name='C6H5OH';productName='C6H5O−';}
else if(['ammonium','methylammonium'].includes(type)){atom(g,center,'N',465,180,type==='ammonium'?3:2,0);bond(g,'proton',center);if(type==='methylammonium')attach(g,'ar','CH3',center,560,115);name=type==='ammonium'?'NH4+':'CH3NH3+';productName=type==='ammonium'?'NH3':'CH3NH2';}
else if(['acetone','acetaldehyde','ethylacetate'].includes(type)){atom(g,center,'C',450,190,2);atom(g,'ac','C',565,120);atom(g,'ao','O',565,5,0,2);bond(g,'proton',center);bond(g,center,'ac');bond(g,'ac','ao',2);if(type==='ethylacetate'){atom(g,'esterO','O',670,190,0,2);bond(g,'ac','esterO');attach(g,'ar','CH2CH3','esterO',670,300)}else attach(g,'ar',type==='acetone'?'CH3':'H','ac',670,190);extra=[move(BD('proton',center),BD(center,'ac')),move(BD('ac','ao'),LP('ao'))];name={acetone:'Acetone',acetaldehyde:'Acetaldehyde',ethylacetate:'Ethyl acetate'}[type];productName=name+' enolate';}
else if(type==='malononitrile'){atom(g,center,'C',470,185,1);atom(g,'cn1','C',545,78);atom(g,'cn2','C',545,292);atom(g,'nn1','N',620,-30,0,1);atom(g,'nn2','N',620,400,0,1);bond(g,'cn1','nn1',3);bond(g,'cn2','nn2',3);bond(g,'proton',center);bond(g,center,'cn1');bond(g,center,'cn2');name='Malononitrile';productName='Dicyanomethyl anion';}
else if(['acetylene','propyne'].includes(type)){atom(g,center,'C',455,180);atom(g,'ac','C',575,180,type==='acetylene'?1:0);if(type==='propyne')attach(g,'ar','CH3','ac',680,180);bond(g,'proton',center);bond(g,center,'ac',3);name=type==='acetylene'?'HC≡CH':'CH3C≡CH';productName=type==='acetylene'?'HC≡C−':'CH3C≡C−';}
return{g,center,name,productName,extra};}
function addAcid(bt,at,level){if(bt==='water'&&at==='hydronium')at='methyloxonium';if((bt==='ammonia'&&at==='ammonium')||(bt==='methylamine'&&at==='methylammonium')||(bt==='acetate'&&at==='acetic'))at='propionic';if(bt==='acetylide'&&at==='acetylene')at='propyne';const b=basePart(bt),a=acidPart(at),g={atoms:[...b.g.atoms,...a.g.atoms],bonds:[...b.g.bonds,...a.g.bonds]},moves=[move(LP(b.donor),BD(b.donor,'proton')),...(a.extra.length?a.extra:[move(BD('proton',a.center),LP(a.center))])],p=apply(g,moves);const donor=p.atoms.find(n=>n.id===b.donor),h=p.atoms.find(n=>n.id==='proton');h.x=donor.x+b.hOffset.x;h.y=donor.y+b.hOffset.y;
QUESTION_BANK.push({id:'a'+String(QUESTION_BANK.filter(q=>q.topic==='acid').length+1).padStart(3,'0'),topic:'acid',level,title:b.name+' + '+a.name,family:level==='hard'?'Carbon-acid proton transfer':level==='moderate'?'Charged species and weak acids':'Simple proton transfer',start:g,product:p,moves,roles:[b.name,a.name,b.productName,a.productName],roleAnswers:['Base','Acid','Conjugate acid','Conjugate base'],components:{base:b.g.atoms.map(n=>n.id),acid:a.g.atoms.map(n=>n.id)},context:'Identify the four acid–base roles, then draw all arrows that give the products shown.',explanation:a.extra.length?'The base takes H+. The C–H pair forms a C=C bond while the C=O π pair goes onto oxygen; all three arrows are needed for the enolate shown.':'The base takes H+ and the original bond to H breaks. Follow the displayed products; these exercises do not ask which side of the equilibrium is favored.'});}
for(const b of ['ammonia','methylamine','dimethylamine','trimethylamine','water','methanol','ethanol'])for(const a of ['HCl','HBr','HI','HF','hydronium'])addAcid(b,a,'easy');
for(const b of ['hydroxide','methoxide','ethoxide','acetate','pyridine','methylamine','ammonia'])for(const a of ['acetic','formic','phenol','ammonium','methylammonium'])addAcid(b,a,'moderate');
for(const b of ['hydroxide','methoxide','amide','acetylide','ammonia','dimethylamine'])for(const a of ['acetone','acetaldehyde','ethylacetate','malononitrile','acetylene'])addAcid(b,a,'hard');

// Curated classroom-sized banks: 20 varied questions at each difficulty.
const ACID_PICKS={
 easy:[1,7,13,19,25,31,2,8,14,20,26,32,3,9,15,21,27,33,4,10],
 moderate:[36,42,48,54,60,66,37,43,49,55,61,67,38,44,50,56,62,68,39,45],
 hard:[71,77,83,89,95,72,78,84,90,96,73,79,85,91,97,74,80,86,92,98]
};
const PRACTICE_BANK=[];
const EXTRA_AROMATIC_IDS=new Set(['rv-h-aromatic-anisole','rv-h-aromatic-benzene','rv-h-aromatic-benzyl-anion','rv-h-aromatic-benzyl-cation','rv-h-aromatic-nitrobenzene']);
for(const level of ['easy','moderate','hard']){const levelQuestions=QUESTION_BANK.filter(q=>q.topic==='resonance'&&q.level===level);PRACTICE_BANK.push(...levelQuestions.slice(0,20));if(level==='hard')PRACTICE_BANK.push(...levelQuestions.filter(q=>EXTRA_AROMATIC_IDS.has(q.id)))}
function swapAcidSides(question){const q=clone(question);for(const g of [q.start,q.product])for(const a of g.atoms)a.x=590-a.x;const[base,acid,conjugateAcid,conjugateBase]=q.roles;q.roles=[acid,base,conjugateBase,conjugateAcid];q.roleAnswers=['Acid','Base','Conjugate base','Conjugate acid'];q.title=acid+' + '+base;q.id+='-swapped';return q}
function randomizedSideMask(size){const positions=Array.from({length:size},(_,i)=>i);for(let i=positions.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[positions[i],positions[j]]=[positions[j],positions[i]]}return new Set(positions.slice(0,Math.floor(size/2)))}
for(const level of ['easy','moderate','hard']){const swapped=randomizedSideMask(ACID_PICKS[level].length);PRACTICE_BANK.push(...ACID_PICKS[level].map((n,i)=>{const q=QUESTION_BANK.find(q=>q.id==='a'+String(n).padStart(3,'0'));return swapped.has(i)?swapAcidSides(q):q}))}
