let topic='intro',level='easy',index=0,questions=[],placed=[],selected=null,drag=null,rolesDone=true,solved=false,hintLevel=0,hintMark=null;
const finished=new Set();const $=id=>document.getElementById(id);const current=()=>questions[index];
function say(s,state='neutral'){const el=$('feedback');el.setAttribute('data-state',state);el.textContent=state==='correct'?'Correct':(state==='incorrect'?'✕ Incorrect — ':'')+s}
function incorrect(s){say(s,'incorrect')}
function controls(){const locked=!rolesDone||solved||topic==='intro';$('undo').hidden=locked;$('clear').hidden=locked;$('check').hidden=solved||topic==='intro';$('hint').hidden=solved;$('check').textContent=rolesDone?'Check arrows':'Check labels';$('next').hidden=!solved;$('next').textContent=index===questions.length-1?(topic==='intro'?'Finish intro →':'Finish level →'):'Next question →'}
function updateProgress(){const n=questions.filter(q=>finished.has(q.id)).length;$('count').textContent=`${topic==='intro'?'INTRO':level.toUpperCase()} · QUESTION ${index+1} / ${questions.length}`;$('score').textContent=`${n} complete`;$('progress').style.width=`${n/questions.length*100}%`}
function roles(){const q=current(),acid=chemistryTopic(q)==='acid';$('left-label').textContent=acid?'Reactants':'Resonance structure A';$('right-label').textContent=acid?'Products':'Resonance structure B';$('relation').innerHTML=relationArrow(acid);$('relation').setAttribute('aria-label',acid?'Acid–base equilibrium':'Resonance: one double-headed arrow');$('reactant-roles').innerHTML='';$('product-roles').innerHTML='';if(!acid||q.topic==='intro')return;
const opts=['Acid','Base','Conjugate acid','Conjugate base'];const make=(i)=>`<label>${esc(pretty(q.roles[i]))}<select id="role-${i}" aria-label="Role of ${esc(q.roles[i])}"><option value="">Choose a role</option>${opts.map(v=>`<option value="${v}">${v}</option>`).join('')}</select></label>`;$('reactant-roles').innerHTML=make(0)+make(1);$('product-roles').innerHTML=make(2)+make(3)}
function defs(){return '<defs></defs>'}

function draw(){if(topic==='intro'){drawIntro();return}const q=current(),ls=layouts(q),v=ls.view,view=`${v.x} ${v.y} ${v.w} ${v.h}`;let html=defs()+molecule(ls.start,q);
for(const a of placed){const route=ls.routes.get(a.source.id+'>'+a.target.key)||routeArrow(ls.start,a.source,a.target,current());html+=arrowPath(route)}
if(rolesDone&&!solved){if(!selected){html+=ls.start.targets.filter(t=>t.atom).map(t=>`<circle class="hit" data-target="${t.key}" cx="${t.x}" cy="${t.y}" r="16"/>`).join('');html+=ls.start.sources.map(s=>`<circle class="hit source" data-source="${esc(s.id)}" cx="${s.x}" cy="${s.y}" r="15" tabindex="0" role="button" aria-label="${esc(s.label)}"/>`).join('')}else{html+=ls.start.targets.map(t=>`<circle class="hit destination" data-target="${esc(t.key)}" cx="${t.x}" cy="${t.y}" r="18" tabindex="0" role="button" aria-label="Destination: ${esc(t.label)}"/>`).join('');const a=selected.angle??-Math.PI/2,t={x:selected.x+Math.cos(a)*42,y:selected.y+Math.sin(a)*42};html+=`<circle class="selected-ring" cx="${selected.x}" cy="${selected.y}" r="11"/><g id="live">${previewPath(selected,t)}<circle id="handle" cx="${t.x}" cy="${t.y}" r="12" tabindex="0" role="button" aria-label="Drag the arrowhead"/></g>`}}
if(hintMark&&!solved){for(const p of hintMark)html+=`<circle class="hint-ring" cx="${p.x}" cy="${p.y}" r="18"/>`}
mountReaction(html,ls,q);const b=$('board');b.addEventListener('pointerdown',pointerDown);b.addEventListener('pointermove',pointerMove);b.addEventListener('pointerup',pointerUp);b.addEventListener('pointercancel',()=>{drag=null;draw()});b.addEventListener('keydown',keyDown)}
function beginQuestion(n=0){index=n;placed=[];selected=null;drag=null;solved=false;hintLevel=0;hintMark=null;rolesDone=current().topic!=='acid';const resonance=topic==='resonance',acid=topic==='acid';$('question-select').value=String(index);$('title').textContent=resonance?'Draw the curly arrow(s) to show the conversion of resonance structure A into resonance structure B.':acid?current().context:current().title;$('title').hidden=false;$('context').textContent=acid||resonance?'':current().context;$('context').hidden=acid||topic==='intro';$('family').textContent=resonance?current().title:current().family;$('instruction').textContent=resonance?'':'Step 1: assign all four acid–base roles. Then draw the complete mechanism.';for(const id of ['family','instruction','keyboard-help'])$(id).hidden=topic==='intro';$('intro-options').hidden=topic!=='intro';$('reaction-grid').hidden=false;$('keyboard-help').hidden=topic==='intro';$('keyboard-help').textContent=topic==='intro'?'Click your answer on the starting structure. Keyboard: Tab to a choice, then Enter or Space.':'Select a pair, then drag its arrowhead or tap its destination. Keyboard: Tab and Enter; Esc clears a selection.';if(topic==='intro')$('instruction').textContent=current().kind==='choice'?'Select one answer.':current().kind==='source'?'Click the electron source on the left-hand structure.':'The orange ring marks the electron source. Click the destination on the left-hand structure.';roles();controls();updateProgress();draw();say('')}
function choose(nextTopic=topic,nextLevel=level){topic=nextTopic;level=nextLevel;questions=topic==='intro'?INTRO:PRACTICE_BANK.filter(q=>q.topic===topic&&q.level===level);for(const t of ['intro','resonance','acid'])$('topic-'+t).setAttribute('aria-pressed',String(t===topic));for(const l of ['easy','moderate','hard'])$('level-'+l).setAttribute('aria-pressed',String(l===level));$('level-picker').hidden=topic==='intro';$('question-select').innerHTML=questions.map((q,i)=>`<option value="${i}">${i+1}. ${esc(q.title)}</option>`).join('');beginQuestion(0)}

function selectSource(id){if(!rolesDone||solved)return false;const s=layouts(current()).start.sources.find(s=>s.id===id);if(!s)return false;if(placed.some(a=>a.source.id===id)){say('That pair is already used. Undo or clear an arrow to revise it.');return false}selected=s;hintMark=null;hintLevel=0;say('Pair selected. Drag the arrowhead, or tap its destination.');draw();return true}
function dropAt(key){if(!selected||solved||!rolesDone)return false;const t=layouts(current()).start.targets.find(t=>t.key===key);if(!t){say('Release on an atom or bond. Your electron pair is still selected.');draw();return false}placed.push({source:selected,target:t});selected=null;hintLevel=0;hintMark=null;say(`${placed.length} arrow${placed.length===1?'':'s'} drawn. Check your answer when the complete set is ready.`);draw();return true}
function checkRoles(){const expected=current().roleAnswers||['Base','Acid','Conjugate acid','Conjugate base'],clues={Acid:'This reactant donates H+. Which role is a proton donor?',Base:'This reactant accepts H+ using an electron pair. Which role is a proton acceptor?','Conjugate acid':'This product is the original base after gaining H+. Which conjugate partner is it?','Conjugate base':'This product is the original acid after losing H+. Which conjugate partner is it?'};for(let i=0;i<4;i++){const el=$('role-'+i);if(!el.value){incorrect('Choose a role for each of the four species.');return false}if(el.value!==expected[i]){incorrect(clues[expected[i]]);el.focus();return false}}rolesDone=true;for(let i=0;i<4;i++)$('role-'+i).disabled=true;hintLevel=0;controls();$('instruction').textContent='Step 2: draw all curly arrows needed to convert the reactants into the products shown.';say('All four roles are correct. Now draw the complete arrow set.','correct');draw();return true}
function checkAnswer(){if(solved)return;if(!rolesDone){checkRoles();return}selected=null;hintMark=null;drag=null;const q=current();if(!placed.length){incorrect('Draw your arrows first. Start each one at a lone pair or a bond.');draw();return}const bad=placed.find(a=>!goodArrow(q,a));if(bad){const matches=sourceMoves(q,bad.source);incorrect(matches.length?'One arrow has the wrong destination. Compare the bond orders and lone pairs in the starting and target structures. Use Hint for a specific cue.':'One arrow starts at a pair that does not move in the transformation shown. Compare the two structures, or use Hint.');draw();return}const used=placed.map(a=>a.source.key+'>'+a.target.key);if(new Set(used).size!==used.length){incorrect('An electron transfer is duplicated. Use one lone pair for each new bond, not two. Undo or clear the extra arrow.');draw();return}const missing=q.moves.filter(m=>!placed.some(a=>a.source.key===locKey(m.from)&&a.target.key===targetForMove(q,m)));if(missing.length){incorrect(q.topic==='resonance'?'Your answer is incomplete. Account for every bond-order and lone-pair change between the two contributors.':'Your answer is incomplete. Account for the broken H bond and any additional bond-order changes in the conjugate base shown.');draw();return}solved=true;finished.add(q.id);controls();updateProgress();$('instruction').textContent='';say(q.explanation,'correct');draw()}
function hint(){if(solved)return;if(topic==='intro'){introHint();return}hintLevel=Math.min(3,hintLevel+1);if(!rolesDone){say(['An acid donates H+; a base accepts H+. Compare each reactant with its product.','The first reactant gains H+ and the second loses H+. Their products are their conjugate partners.','From left to right: Base, Acid, Conjugate acid, Conjugate base.'][hintLevel-1]);return}const q=current(),ls=layouts(q);const m=q.moves.find(m=>!placed.some(a=>a.source.key===locKey(m.from)&&a.target.key===targetForMove(q,m)))||q.moves[0];const s=ls.start.sources.find(s=>s.key===locKey(m.from)),t=ls.start.targets.find(t=>t.key===targetForMove(q,m));if(hintLevel===1){say('Hint 1/3: '+(m.from.type==='lp'?'Look for a lone pair that becomes a bond. The arrow must begin at those electrons.':'Look for a bond that loses one electron pair. The arrow begins on that bond.'))}else if(hintLevel===2){say('Hint 2/3: Start at '+s.label.toLowerCase()+'. '+(m.to.type==='lp'?'That pair becomes a lone pair on an atom.':'That pair supplies a new bond or increases a bond order.'));hintMark=[s]}else{say('Hint 3/3: Move the highlighted electron pair to the highlighted '+(t.atom?'atom':'bond')+'.');hintMark=[s,t]}draw()}
function point(e){return new DOMPoint(e.clientX,e.clientY).matrixTransform($('board').getScreenCTM().inverse())}
function targetAt(p){const l=layouts(current()).start;return l.targets.map(t=>({...t,d:dist(p,t)})).filter(t=>t.d<25).sort((a,b)=>a.d-b.d)[0]?.key}
function pointerDown(e){if(!rolesDone||solved||e.button>0)return;const p=point(e),n=e.target;if(n.dataset.source){if(!selectSource(n.dataset.source))return}else if(n.id==='handle'&&selected){}else if(n.dataset.target){if(selected)dropAt(n.dataset.target);else say('Begin at a lone pair or bonding pair, not at an atom.');return}else return;e.preventDefault();$('board').setPointerCapture(e.pointerId);drag={id:e.pointerId,start:p,moved:false}}
function pointerMove(e){if(!drag||drag.id!==e.pointerId||!selected)return;const p=point(e);if(dist(p,drag.start)>5)drag.moved=true;if(!drag.moved)return;e.preventDefault();const ls=layouts(current()),key=targetAt(p),target=ls.start.targets.find(t=>t.key===key);let path,end=p;if(target){const cacheKey=selected.id+'>'+target.key;let route=ls.routes.get(cacheKey);if(!route){route=routeArrow(ls.start,selected,target,current());ls.routes.set(cacheKey,route)}path=arrowPath(route);end=route.e}else path=previewPath(selected,p);$('live').innerHTML=path+`<circle id="handle" cx="${end.x}" cy="${end.y}" r="12"/>`;}

function pointerUp(e){if(!drag||drag.id!==e.pointerId)return;const a=drag;drag=null;if(a.moved)dropAt(targetAt(point(e)))}
function keyDown(e){if(e.key==='Escape'){selected=null;drag=null;draw();say('Selection cleared.');return}if(e.key!=='Enter'&&e.key!==' ')return;e.preventDefault();if(e.target.dataset.source){selectSource(e.target.dataset.source);$('board').querySelector('.destination')?.focus()}else if(e.target.dataset.target&&selected)dropAt(e.target.dataset.target)}
$('intro-options').onclick=e=>{const b=e.target.closest('[data-option]');if(b)introPick(b.dataset.option)};$('check').onclick=checkAnswer;$('hint').onclick=hint;
$('undo').onclick=()=>{placed.pop();selected=null;hintMark=null;hintLevel=0;say('Last arrow removed.');draw()};$('clear').onclick=()=>{placed=[];selected=null;hintMark=null;hintLevel=0;say('Arrows cleared. Try again.');draw()};
$('next').onclick=()=>{if(index<questions.length-1){beginQuestion(index+1)}else{say(topic==='intro'?'Intro complete. Choose Resonance or Acid–base to practice drawing whole mechanisms.':'You reached the end of this level. Use the question picker to revisit any examples, or choose another level.');$('next').hidden=true}};
$('reset').onclick=()=>beginQuestion(index);$('question-select').onchange=e=>beginQuestion(Number(e.target.value));for(const t of ['intro','resonance','acid'])$('topic-'+t).onclick=()=>choose(t,level);for(const l of ['easy','moderate','hard'])$('level-'+l).onclick=()=>choose(topic,l);choose();
