const INTRO=[];
function concept(title,options,answer,feedback,hint){INTRO.push({id:'i'+(INTRO.length+1),topic:'intro',kind:'choice',title,options,answer,feedback,hint,family:'Arrow essentials',context:'Choose one answer. You can retry as often as you need.'})}
concept('What does a full-headed curly arrow represent?', ['The movement of one electron','The movement of a pair of electrons','The movement of an atom','The direction a molecule travels'],1,['One electron is represented by a single-barbed fishhook arrow. A full arrowhead represents two electrons.','A full-headed curly arrow shows the movement of two electrons: one electron pair.','Atoms are not what a curly arrow tracks. It tracks electrons.','A curly arrow tracks electrons within or between species, not molecular travel.'],'Count electrons: a full arrowhead represents a pair.');
concept('Where should a curly arrow start?', ['At a positive charge','At the atom receiving electrons','At a lone pair or a bond','Anywhere near a molecule'],2,['A positive charge often marks an electron-poor site, not a source of electrons.','The receiving site is the destination. Start at the electrons that move.','Start at an existing electron pair: a lone pair or a bonding pair.','The tail must identify the actual electron pair that moves.'],'The tail identifies the source of the electrons.');
concept('What does the arrowhead tell you?', ['Where the electron pair goes','Which molecule is the largest','Where the electrons started','Which atom moves'],0,['The arrowhead points to the destination: an atom receiving a lone pair, a bond being formed, or a bond gaining a pair.','Molecular size does not determine the arrowhead position.','The tail marks the source; the head marks the destination.','Curly arrows track electrons rather than atom movement.'],'Read the arrow from tail to head: source to destination.');
concept('What changes between resonance contributors?', ['The positions of the atoms','The total charge','The number of electrons','The placement of electrons and bond orders'],3,['The atomic framework stays fixed in resonance.','The total charge is conserved, although individual formal charges can change.','Resonance conserves the total number of electrons.','Electron placement and bond orders can change; the atomic framework and total charge stay the same.'],'Resonance contributors are different electron arrangements for one species.');
concept('Which connector belongs between resonance contributors?', ['A single reaction arrow (→)','One double-headed arrow (↔)','Opposing equilibrium arrows (⇌)','A full-headed curly arrow'],1,['A single reaction arrow denotes a reaction direction, not resonance.','Use one double-headed straight arrow between resonance contributors.','Equilibrium arrows connect different species in equilibrium, not resonance contributors.','Curly arrows show electron movement on a structure. They do not replace the connector between contributors.'],'Resonance is not an equilibrium between two different species.');
concept('Which arrows should be used to show equilibrium in an acid–base reaction?', ['A single reaction arrow (→)','One double-headed resonance arrow (↔)','Opposing equilibrium arrows (⇌)','A curly arrow'],2,['A single reaction arrow does not show equilibrium.','A double-headed resonance arrow connects resonance contributors, not reactants and products in equilibrium.','Correct','A curly arrow shows electron movement, not equilibrium between reactants and products.'],'Equilibrium is represented by two opposing arrows, one for each direction.');

function guided(id,kind,moveIndex,prompt,tip,explanation){const q=clone(QUESTION_BANK.find(q=>q.id===id));q.exampleId=id;q.chemistryTopic=q.topic;q.topic='intro';q.id='i'+(INTRO.length+1);q.kind=kind;q.focusMove=moveIndex;q.title=q.chemistryTopic==='resonance'?(kind==='source'?'Where does the curly arrow need to start to convert resonance structure A into resonance structure B?':'Where does the curly arrow need to end to convert resonance structure A into resonance structure B?'):(kind==='source'?'Where does the curly arrow need to start to convert the reactants into the products shown?':'Where does the curly arrow need to end to convert the reactants into the products shown?');q.context=pretty(QUESTION_BANK.find(q=>q.id===id).title)+(q.chemistryTopic==='resonance'?' · Compare resonance structures A and B.':' · Compare the reactants and products.');if(kind==='source'&&q.moves.length>1){const m=q.moves[moveIndex];q.context+=' Focus on '+(m.to.type==='bond'?(m.to.a==='proton'||m.to.b==='proton'?'formation of the new bond to H.':'the bond that increases in order.'):'the pair that becomes a lone pair in the target.');}q.family=q.chemistryTopic==='resonance'?'Resonance · '+(kind==='source'?'find the electron source':'find the destination'):'Acid–base · '+(kind==='source'?'find the electron source':'find the destination');q.hint=tip;q.explanation=explanation;INTRO.push(q)}
guided('rv-e-nitrile-acetonitrile','source',0,'','Compare resonance structures A and B. Look for the bond-order and lone-pair changes.','');
guided('r022','target',0,'','Compare resonance structures A and B. Look for the bond-order and lone-pair changes.','');
guided('rv-e-oxo-CH3','source',0,'','Compare resonance structures A and B. Look for the bond-order and lone-pair changes.','');
guided('r025','source',0,'','Compare resonance structures A and B. Look for the bond-order and lone-pair changes.','');
guided('r008','target',0,'','Compare resonance structures A and B. Look for the bond-order and lone-pair changes.','');
guided('r029','target',0,'','Compare resonance structures A and B. Look for the bond-order and lone-pair changes.','');
guided('r031','source',0,'','Compare resonance structures A and B. Look for the bond-order and lone-pair changes.','');
guided('r033','target',0,'','Compare resonance structures A and B. Look for the bond-order and lone-pair changes.','');
guided('r035','source',0,'','Compare resonance structures A and B. Look for the bond-order and lone-pair changes.','');

function introComplete(text){solved=true;hintMark=null;finished.add(current().id);controls();updateProgress();drawIntro();$('instruction').textContent='';say(text,'correct')}
function introPick(key){if(solved)return;const q=current();if(q.kind==='choice'){const i=Number(key);if(i===q.answer)introComplete(q.feedback[i]);else incorrect(q.feedback[i]);return}const l=layouts(q).start,m=q.moves[q.focusMove];let ok;if(q.kind==='source'){const s=l.sources.find(s=>s.id===key);ok=s?.key===locKey(m.from)}else ok=key===targetForMove(q,m);if(ok){if(q.kind==='source')selected=l.sources.find(s=>s.id===key);introComplete(q.kind==='source'?'You identified the electron pair that supplies this change.':'You identified where this electron pair goes in the displayed change.');}else{const atom=key.startsWith('atom:');incorrect((q.kind==='source'&&atom?'Start at electrons—a lone pair or a bond—not at an atom label. ':q.kind==='target'&&m.to.type==='lp'?'This pair becomes a lone pair, so choose the receiving atom. ':q.kind==='target'&&targetForMove(q,m).startsWith('bond:')?'This pair increases a bond order, so choose the receiving bond. ':'That is not the electron source or destination for the change in this question. ')+q.hint)}}
function introHint(){say(current().hint);if(current().kind==='choice')return;const q=current(),l=layouts(q).start,m=q.moves[q.focusMove];hintLevel++;if(hintLevel>=2){hintMark=q.kind==='source'?l.sources.filter(s=>s.key===locKey(m.from)):[l.targets.find(t=>t.key===targetForMove(q,m))];drawIntro()}}
function drawIntro(){const q=current();$('intro-options').hidden=q.kind!=='choice';$('reaction-grid').hidden=q.kind==='choice';$('keyboard-help').hidden=true;if(q.kind==='choice'){$('intro-options').innerHTML=q.options.map((o,i)=>`<button data-option="${i}" ${solved?'disabled':''}>${esc(o)}</button>`).join('');return}const ls=layouts(q),l=ls.start,v=ls.view,view=`${v.x} ${v.y} ${v.w} ${v.h}`,m=q.moves[q.focusMove];let html=defs()+molecule(l,q);if(solved){const source=selected||l.sources.find(s=>s.key===locKey(m.from)),target=l.targets.find(t=>t.key===targetForMove(q,m));html+='<g class="answer-arrow">'+arrowPath(ls.routes.get(source.id+'>'+target.key)||routeArrow(l,source,target))+'</g>';}else{if(q.kind==='target'){const s=l.sources.find(s=>s.key===locKey(m.from));html+=`<circle class="intro-origin" cx="${s.x}" cy="${s.y}" r="12"/>`;}const choices=q.kind==='source'?[...l.targets.filter(t=>t.atom).map(t=>({...t,choice:t.key})),...l.sources.map(s=>({...s,choice:s.id}))]:l.targets.map(t=>({...t,choice:t.key}));html+=choices.map(t=>`<circle class="hit intro-hit" data-pick="${esc(t.choice)}" cx="${t.x}" cy="${t.y}" r="${q.kind==='source'?13:17}" tabindex="0" role="button" aria-label="${esc(t.label)}"/>`).join('');if(hintMark)for(const p of hintMark)html+=`<circle class="hint-ring" cx="${p.x}" cy="${p.y}" r="18"/>`;}
mountReaction(html,ls,q);const b=$('board');b.addEventListener('click',e=>{if(e.target.dataset.pick)introPick(e.target.dataset.pick)});b.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.pick){e.preventDefault();introPick(e.target.dataset.pick)}})}
