(()=>{
const $=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg';
const Q=(level,name,conf,f,b)=>({level,name,conf,f,b});
const questions=[
Q('easy','Butane — anti','staggered',['CH₃','H','H'],['CH₃','H','H']),Q('easy','Butane — gauche','staggered',['CH₃','H','H'],['H','CH₃','H']),Q('easy','Pentane viewed along C2–C3','staggered',['CH₃','H','H'],['CH₂CH₃','H','H']),Q('easy','Pentane viewed along C3–C4','staggered',['CH₂CH₃','H','H'],['CH₃','H','H']),Q('easy','Hexane viewed along C3–C4','staggered',['CH₂CH₃','H','H'],['CH₂CH₃','H','H']),Q('easy','2-Methylbutane','staggered',['CH₃','CH₃','H'],['CH₃','H','H']),Q('easy','2-Methylpentane','staggered',['CH₃','CH₃','H'],['CH₂CH₃','H','H']),Q('easy','3-Methylpentane','staggered',['CH₃','H','H'],['CH₂CH₃','CH₃','H']),Q('easy','2,3-Dimethylbutane','staggered',['CH₃','CH₃','H'],['CH₃','CH₃','H']),Q('easy','3-Ethylpentane','staggered',['CH₃','H','H'],['CH₂CH₃','CH₂CH₃','H']),
Q('easy','Heptane viewed along C3–C4','staggered',['CH₂CH₃','H','H'],['CH₂CH₃','H','H']),Q('easy','Heptane viewed along C2–C3','staggered',['CH₃','H','H'],['CH₂CH₃','H','H']),Q('easy','2-Methylhexane','staggered',['CH₃','CH₃','H'],['CH₂CH₃','H','H']),Q('easy','3-Methylhexane','staggered',['CH₂CH₃','H','H'],['CH₂CH₃','CH₃','H']),Q('easy','2,4-Dimethylpentane','staggered',['CH₃','CH₃','H'],['CH(CH₃)₂','H','H']),Q('easy','3-Ethylhexane','staggered',['CH₂CH₃','H','H'],['CH₂CH₃','CH₂CH₃','H']),Q('easy','2,3-Dimethylpentane','staggered',['CH₃','CH₃','H'],['CH₂CH₃','CH₃','H']),Q('easy','Octane viewed along C4–C5','staggered',['CH₂CH₃','H','H'],['CH₂CH₃','H','H']),Q('easy','2-Methylpentane — alternate staggered conformer','staggered',['CH₃','H','CH₃'],['CH₂CH₃','H','H']),Q('easy','3-Methylpentane — alternate staggered conformer','staggered',['CH₃','H','H'],['H','CH₃','CH₂CH₃']),
Q('moderate','3-Methylpentane','staggered',['CH₃','H','H'],['CH₂CH₃','CH₃','H']),Q('moderate','2,3-Dimethylbutane','staggered',['CH₃','CH₃','H'],['CH₃','CH₃','H']),Q('moderate','2,3-Dimethylbutane — alternate staggered conformer','staggered',['CH₃','CH₃','H'],['CH₃','H','CH₃']),Q('moderate','3-Ethylpentane','staggered',['CH₃','H','H'],['CH₂CH₃','CH₂CH₃','H']),Q('moderate','2-Methylpentane','staggered',['CH₃','CH₃','H'],['CH₂CH₃','H','H']),Q('moderate','3-Methylhexane','staggered',['CH₂CH₃','H','H'],['CH₂CH₃','CH₃','H']),Q('moderate','2,4-Dimethylpentane','staggered',['CH₃','CH₃','H'],['CH(CH₃)₂','H','H']),Q('moderate','3,3-Dimethylpentane','staggered',['CH₂CH₃','H','H'],['CH₂CH₃','CH₃','CH₃']),Q('moderate','2,2,3-Trimethylbutane','staggered',['CH₃','CH₃','CH₃'],['CH₃','CH₃','H']),Q('moderate','Hexane viewed along C3–C4','staggered',['CH₂CH₃','H','H'],['CH₂CH₃','H','H']),
Q('moderate','2,3-Dimethylpentane','staggered',['CH₃','CH₃','H'],['CH₂CH₃','CH₃','H']),Q('moderate','2,3,4-Trimethylpentane','staggered',['CH(CH₃)₂','CH₃','H'],['CH₃','CH₃','H']),Q('moderate','3-Ethyl-2-methylpentane','staggered',['CH₃','CH₃','H'],['CH₂CH₃','CH₂CH₃','H']),Q('moderate','3,4-Dimethylhexane','staggered',['CH₂CH₃','CH₃','H'],['CH₂CH₃','CH₃','H']),Q('moderate','2,2,3-Trimethylpentane','staggered',['CH₃','CH₃','CH₃'],['CH₂CH₃','CH₃','H']),Q('moderate','3-Ethyl-2-methylhexane','staggered',['CH₃','CH₃','H'],['CH₂CH₃','CH₂CH₃','H']),Q('moderate','2,4-Dimethylhexane','staggered',['CH₃','CH₃','H'],['CH₂CH₃','CH(CH₃)₂','H']),Q('moderate','3,3-Diethylpentane','staggered',['CH₂CH₃','CH₂CH₃','H'],['CH₂CH₃','CH₂CH₃','CH₃']),Q('moderate','2,2,4-Trimethylpentane','staggered',['CH₃','CH₃','CH₃'],['CH(CH₃)₂','H','H']),Q('moderate','3-Ethyl-2,4-dimethylpentane','staggered',['CH(CH₃)₂','H','H'],['CH(CH₃)₂','CH₂CH₃','H']),
Q('hard','2,3,4-Trimethylpentane','staggered',['CH(CH₃)₂','CH₃','H'],['CH₃','CH₃','H']),Q('hard','2,2,3,4-Tetramethylpentane','staggered',['C(CH₃)₃','CH₃','H'],['CH(CH₃)₂','CH₃','H']),Q('hard','3-Ethyl-2-methylpentane','staggered',['CH₃','CH₃','H'],['CH₂CH₃','CH₂CH₃','H']),Q('hard','3-Ethyl-2,4-dimethylpentane','staggered',['CH(CH₃)₂','H','H'],['CH(CH₃)₂','CH₂CH₃','H']),Q('hard','2,2,3-Trimethylpentane','staggered',['C(CH₃)₃','H','H'],['CH₂CH₃','CH₃','H']),Q('hard','3,4-Diethylhexane','staggered',['CH₂CH₃','CH₂CH₃','H'],['CH₂CH₃','CH₂CH₃','H']),Q('hard','2,3-Dimethylhexane','staggered',['CH(CH₃)₂','H','H'],['CH₂CH₃','CH₃','H']),Q('hard','2,2,3,3-Tetramethylbutane','staggered',['CH₃','CH₃','CH₃'],['CH₃','CH₃','CH₃']),Q('hard','3-Ethyl-2,2-dimethylpentane','staggered',['C(CH₃)₃','H','H'],['CH₂CH₃','CH₂CH₃','H']),Q('hard','4-Ethyl-2,3-dimethylhexane','staggered',['CH(CH₃)₂','CH₃','H'],['CH₂CH₃','CH₂CH₃','H']),
Q('hard','2,2,3,4,4-Pentamethylpentane','staggered',['C(CH₃)₃','CH₃','H'],['C(CH₃)₃','CH₃','H']),Q('hard','3,4-Diethyl-2,5-dimethylhexane','staggered',['CH(CH₃)₂','CH₂CH₃','H'],['CH(CH₃)₂','CH₂CH₃','H']),Q('hard','3-Ethyl-2,2,4-trimethylpentane','staggered',['C(CH₃)₃','H','H'],['CH(CH₃)₂','CH₂CH₃','H']),Q('hard','3,4-Diethyl-2-methylhexane','staggered',['CH(CH₃)₂','CH₂CH₃','H'],['CH₂CH₃','CH₂CH₃','H']),Q('hard','2,2,3,4-Tetramethylhexane','staggered',['C(CH₃)₃','CH₃','H'],['CH₂CH₃','CH(CH₃)₂','H']),Q('hard','3,3,4-Trimethylhexane','staggered',['CH₂CH₃','CH₃','CH₃'],['CH₂CH₃','CH₃','H']),Q('hard','3,4-Diethyl-2,2-dimethylhexane','staggered',['C(CH₃)₃','H','H'],['CH₂CH₃','CH₂CH₃','CH₃']),Q('hard','2,3,3,4-Tetramethylpentane','staggered',['CH(CH₃)₂','CH₃','H'],['C(CH₃)₃','CH₃','H']),Q('hard','4-Ethyl-2,2,3-trimethylhexane','staggered',['C(CH₃)₃','CH₃','H'],['CH₂CH₃','CH₂CH₃','CH₃']),Q('hard','3,4-Diisopropylhexane','staggered',['CH(CH₃)₂','CH₂CH₃','H'],['CH(CH₃)₂','CH₂CH₃','H'])];
const rtlQuestions=new Set([1,3,4,6,9,10,12,15,17,18]);
for(const difficulty of ['easy','moderate','hard'])questions.filter(q=>q.level===difficulty).forEach((q,i)=>q.dir=rtlQuestions.has(i)?'rtl':'ltr');
let mode='to',level='easy',index=0,score=0,attempts=0,selected=null,placed=Array(6).fill(null),hintLevel=0,answered=false;
const active=()=>questions.filter(x=>x.level===level),svgEl=(tag,a={})=>{const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))e.setAttribute(k,v);return e};
const angles=(conf,front)=>front?[-90,30,150]:(conf==='staggered'?[90,210,-30]:[-90,30,150]);
function point(cx,cy,r,d){const a=d*Math.PI/180;return{x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r}}
function slotNames(item,type){if(type==='newman')return item.conf==='staggered'?['front top','front lower right','front lower left','back bottom','back upper left','back upper right']:['front top','front lower right','front lower left','back top','back lower right','back lower left'];return item.conf==='staggered'?['front carbon in-plane upper bond','front carbon hashed-wedge bond','front carbon solid-wedge bond','back carbon in-plane lower bond','back carbon solid-wedge bond','back carbon hashed-wedge bond']:['front carbon in-plane upper bond','front carbon hashed-wedge bond','front carbon solid-wedge bond','back carbon in-plane upper bond','back carbon solid-wedge bond','back carbon hashed-wedge bond']}
function chemicalContent(t,value,subSize=17){t.replaceChildren();const sub='₀₁₂₃₄₅₆₇₈₉';for(const c of value){const i=sub.indexOf(c);if(i<0)t.append(document.createTextNode(c));else{const s=svgEl('tspan',{'baseline-shift':'sub','font-size':subSize});s.textContent=i;t.append(s)}}}
function text(svg,x,y,value,cls='projection-label'){const t=svgEl('text',{x,y,class:cls,'text-anchor':'middle','dominant-baseline':'central'});chemicalContent(t,value);svg.append(t)}
function labelGeometry(center,ux,uy,value,gap=8){const halfW=ux<-.28&&value==='CH₂CH₃'?30:10,halfH=14,reach=Math.min(Math.abs(ux)>1e-6?halfW/Math.abs(ux):Infinity,Math.abs(uy)>1e-6?halfH/Math.abs(uy):Infinity),clearance=value==='H'?gap:3;return{end:{x:center.x-ux*(reach+clearance),y:center.y-uy*(reach+clearance)}}}
function groupPart(svg,x,y,value,anchor){if(!value)return;const t=svgEl('text',{x,y,class:'projection-label','dominant-baseline':'central','text-anchor':anchor});chemicalContent(t,value);svg.append(t)}
const attachmentLayouts={
 left:{'CH₃':['H₃',''],'CH₂CH₃':['CH₃','H₂'],'CH(CH₃)₂':['(CH₃)₂H',''],'C(CH₃)₃':['(CH₃)₃','']},
 right:{'CH₃':['','H₃'],'CH₂CH₃':['','H₂CH₃'],'CH(CH₃)₂':['','H(CH₃)₂'],'C(CH₃)₃':['','(CH₃)₃']}
};
function groupText(svg,center,value,ux){
 if(value==='H'){text(svg,center.x,center.y,value);return}
 const parts=ux<-.28?attachmentLayouts.left:attachmentLayouts.right;
 const [prefix,suffix]=parts[value]||['',value];
 groupPart(svg,center.x-10,center.y,prefix,'end');
 text(svg,center.x,center.y,'C');
 groupPart(svg,center.x+10,center.y,suffix,'start');
}
function slotEnd(center,ux,uy){const reach=Math.min(Math.abs(ux)>1e-6?57/Math.abs(ux):Infinity,Math.abs(uy)>1e-6?22/Math.abs(uy):Infinity);return{x:center.x-ux*(reach+7),y:center.y-uy*(reach+7)}}
function newmanPoints(item){const fr=item.conf==='eclipsed'?105:138,br=item.conf==='eclipsed'?154:152;return[...angles(item.conf,true).map(a=>point(320,180,fr,a)),...angles(item.conf,false).map(a=>point(320,180,br,a))]}
function drawNewman(svg,item,values=null){svg.replaceChildren();const cx=320,cy=180,r=64,slots=newmanPoints(item),labels=[];angles(item.conf,false).forEach((a,i)=>{const slot=i+3,u=point(0,0,1,a),center=values?point(cx,cy,150,a):slots[slot],answerValue=values?null:placed[slot]?.label,g=values?labelGeometry(center,u.x,u.y,item.b[i]):answerValue?labelGeometry(center,u.x,u.y,answerValue):{end:slotEnd(center,u.x,u.y)};labels.push(values?{center,value:item.b[i],ux:u.x}:null);const start=point(cx,cy,r,a);svg.append(svgEl('line',{x1:start.x,y1:start.y,x2:g.end.x,y2:g.end.y,class:'projection-bond newman-rear-bond','data-slot':slot}))});svg.append(svgEl('circle',{cx,cy,r,class:'newman-back'}));angles(item.conf,true).forEach((a,i)=>{const slot=i,u=point(0,0,1,a),center=values?point(cx,cy,150,a):slots[slot],answerValue=values?null:placed[slot]?.label,g=values?labelGeometry(center,u.x,u.y,item.f[i]):answerValue?labelGeometry(center,u.x,u.y,answerValue):{end:slotEnd(center,u.x,u.y)};labels.push(values?{center,value:item.f[i],ux:u.x}:null);svg.append(svgEl('line',{x1:cx,y1:cy,x2:g.end.x,y2:g.end.y,class:'projection-bond newman-front-bond','data-slot':slot}))});svg.append(svgEl('circle',{cx,cy,r:2,class:'newman-front'}));if(values)labels.filter(Boolean).forEach(l=>groupText(svg,l.center,l.value,l.ux));else addSlots(svg,item,'newman')}
function sawPoints(item){const a={x:270,y:180},b={x:390,y:180};if(item.dir==='rtl'){const front=[[85,-85],[25,125],[115,55]],back=[[-85,85],[-115,-55],[-25,-125]];return[...front.map(([x,y])=>({x:b.x+x,y:b.y+y})),...back.map(([x,y])=>({x:a.x+x,y:a.y+y}))]}const front=[[-85,-85],[-25,125],[-115,55]],back=[[85,85],[115,-55],[25,-125]];return[...front.map(([x,y])=>({x:a.x+x,y:a.y+y})),...back.map(([x,y])=>({x:b.x+x,y:b.y+y}))]}
function stereoBond(svg,c,p,type){if(type==='line'){svg.append(svgEl('line',{x1:c.x,y1:c.y,x2:p.x,y2:p.y,class:'projection-bond'}));return}const dx=p.x-c.x,dy=p.y-c.y,n=Math.hypot(dx,dy),px=-dy/n,py=dx/n;if(type==='wedge'){svg.append(svgEl('path',{d:`M ${c.x} ${c.y} L ${p.x+px*11} ${p.y+py*11} L ${p.x-px*11} ${p.y-py*11} Z`,class:'stereo-wedge'}));return}for(let i=1;i<=7;i++){const t=i/8,x=c.x+dx*t,y=c.y+dy*t,w=1+i*1.25;svg.append(svgEl('line',{x1:x-px*w,y1:y-py*w,x2:x+px*w,y2:y+py*w,class:'stereo-hash'}))}}
function viewingArrow(svg,item){if(item.dir==='rtl')svg.append(svgEl('line',{x1:572,y1:180,x2:438,y2:180,class:'view-arrow'}),svgEl('path',{d:'M 422 180 L 438 172 L 438 188 Z',class:'view-arrowhead'}));else svg.append(svgEl('line',{x1:68,y1:180,x2:222,y2:180,class:'view-arrow'}),svgEl('path',{d:'M 238 180 L 222 172 L 222 188 Z',class:'view-arrowhead'}))}
function drawSawhorse(svg,item,values=null){svg.replaceChildren();const a={x:270,y:180},b={x:390,y:180},pts=sawPoints(item),types=['line','dash','wedge','line','wedge','dash'],frontCarbon=item.dir==='rtl'?b:a,backCarbon=item.dir==='rtl'?a:b;svg.append(svgEl('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'projection-bond central'}));viewingArrow(svg,item);pts.forEach((p,i)=>{const c=i<3?frontCarbon:backCarbon,dx=p.x-c.x,dy=p.y-c.y,n=Math.hypot(dx,dy),ux=dx/n,uy=dy/n,answerValue=values?null:placed[i]?.label,g=values?labelGeometry(p,ux,uy,values[i],types[i]==='line'?10:15):answerValue?labelGeometry(p,ux,uy,answerValue,types[i]==='line'?10:15):{end:slotEnd(p,ux,uy)};stereoBond(svg,c,g.end,types[i]);if(values)groupText(svg,p,values[i],ux)});if(!values)addSlots(svg,item,'sawhorse')}
function addSlots(svg,item,type){const pts=type==='newman'?newmanPoints(item):sawPoints(item),names=slotNames(item,type),a={x:270,y:180},b={x:390,y:180},frontCarbon=item.dir==='rtl'?b:a,backCarbon=item.dir==='rtl'?a:b;pts.forEach((p,i)=>{const c=type==='newman'?{x:320,y:180}:i<3?frontCarbon:backCarbon,dx=p.x-c.x,dy=p.y-c.y,n=Math.hypot(dx,dy),g=svgEl('g',{class:'np-slot','data-slot':i,'data-position':names[i],'data-x':p.x,'data-y':p.y,'data-ux':dx/n,tabindex:0,role:'button','aria-label':names[i]});g.append(svgEl('rect',{x:p.x-57,y:p.y-22,width:114,height:44,rx:12}),svgEl('text',{x:p.x,y:p.y,'text-anchor':'middle','dominant-baseline':'central'}));svg.append(g)});renderSlots()}
function renderSlots(){document.querySelectorAll('.np-slot').forEach(g=>{const i=+g.dataset.slot,v=placed[i],t=g.querySelector('text'),where=g.dataset.position;g.querySelectorAll('.projection-label').forEach(x=>x.remove());if(v){t.textContent='';groupText(g,{x:+g.dataset.x,y:+g.dataset.y},v.label,+g.dataset.ux)}else t.textContent='+';g.classList.toggle('filled',!!v);g.setAttribute('aria-label',v?`${where}: ${v.label}. Select to remove.`:`Empty ${where}`)})}
function drawTarget(){const item=active()[index];if(mode==='to')drawNewman($('#np-target'),item);else drawSawhorse($('#np-target'),item)}
function pieces(item){const box=$('#np-pieces'),vals=expected(item);box.replaceChildren();vals.forEach((label,i)=>{const b=document.createElement('button');b.textContent=label;b.dataset.piece=i;b.draggable=true;b.className='np-piece';b.setAttribute('aria-pressed','false');b.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',i)});box.append(b)})}
function assign(piece,slot){const prior=placed.findIndex(x=>x&&x.id===piece.id);if(prior>=0)placed[prior]=null;if(placed[slot])$('#np-pieces').querySelector(`[data-piece="${placed[slot].id}"]`).disabled=false;placed[slot]=piece;$('#np-pieces').querySelector(`[data-piece="${piece.id}"]`).disabled=true;selected=null;document.querySelectorAll('.np-piece').forEach(x=>x.setAttribute('aria-pressed','false'));drawTarget()}
function sourceValues(item){return[...item.f,...item.b]}
function convertedValues(item){return item.dir==='rtl'?sourceValues(item):[item.f[0],item.f[2],item.f[1],item.b[0],item.b[2],item.b[1]]}
function expected(item){return convertedValues(item)}
function correct(item){const got=placed.map(x=>x?.label);if(got.some(x=>!x))return false;const want=expected(item);if(mode==='from')return got.every((v,i)=>v===want[i]);for(let k=0;k<3;k++){let ok=true;for(let side=0;side<2;side++)for(let i=0;i<3;i++)if(got[side*3+i]!==want[side*3+(i+k)%3])ok=false;if(ok)return true}return false}
function feedback(s,state=''){const e=$('#np-feedback');e.dataset.state=state;e.textContent=s}
function render(){const item=active()[index],total=active().length;placed=Array(6).fill(null);selected=null;hintLevel=0;answered=false;$('#np-family').textContent=`${level[0].toUpperCase()+level.slice(1)} · ${item.conf[0].toUpperCase()+item.conf.slice(1)} · View ${item.dir==='rtl'?'right → left':'left → right'}`;$('#np-prompt').textContent=mode==='to'?'Build the Newman projection shown by this perspective drawing.':'Build the perspective drawing represented by this Newman projection.';$('#np-view-note').textContent='View along the indicated C–C bond in the direction of the arrow. The carbon nearest the arrow is the front carbon.';$('#np-source-title').textContent=mode==='to'?'Perspective drawing':'Newman projection';$('#np-target-title').textContent=mode==='to'?'Your Newman projection':'Your perspective drawing';if(mode==='to'){drawSawhorse($('#np-source'),item,sourceValues(item));drawNewman($('#np-target'),item)}else{drawNewman($('#np-source'),item,sourceValues(item));drawSawhorse($('#np-target'),item)};pieces(item);$('#np-count').textContent=`${level.toUpperCase()} · QUESTION ${index+1} / ${total}`;$('#np-progress').style.width=`${((index+1)/total)*100}%`;$('#np-question').value=index;feedback('Place all six groups before checking your answer.')}
function fill(){const s=$('#np-question');s.replaceChildren();active().forEach((_,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`Question ${i+1}`;s.append(o)});render()}
document.addEventListener('click',e=>{const p=e.target.closest('.np-piece');if(p&&!p.disabled){selected=+p.dataset.piece;document.querySelectorAll('.np-piece').forEach(x=>x.setAttribute('aria-pressed',String(x===p)));return}const slot=e.target.closest('.np-slot');if(!slot)return;const i=+slot.dataset.slot;if(placed[i]){const id=placed[i].id;placed[i]=null;$('#np-pieces').querySelector(`[data-piece="${id}"]`).disabled=false;drawTarget()}else if(selected!==null){const label=expected(active()[index])[selected];assign({id:selected,label},i)}});$('#np-target').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.np-slot')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}))}});$('#np-target').addEventListener('dragover',e=>e.preventDefault());$('#np-target').addEventListener('drop',e=>{e.preventDefault();const slot=e.target.closest('.np-slot');if(!slot)return;const id=+e.dataTransfer.getData('text/plain'),label=expected(active()[index])[id];assign({id,label},+slot.dataset.slot)});
$('#np-check').onclick=()=>{if(answered)return;attempts++;const item=active()[index];if(correct(item)){score++;answered=true;feedback('Correct.','correct')}else feedback(placed.some(x=>!x)?'Incorrect — place all six groups before checking.':'Incorrect — check which groups are attached to the front and back carbons, then compare their relative positions.','incorrect');$('#np-score').textContent=`Score: ${score} / ${attempts}`};$('#np-hint').onclick=()=>{const item=active()[index];hintLevel=Math.min(3,hintLevel+1);feedback(hintLevel===1?'Hint 1/3: The carbon nearest the viewing arrow is the front carbon; the other is the back carbon.':hintLevel===2?`Hint 2/3: The conformation is ${item.conf}. Keep the three groups on each carbon 120° apart.`:`Hint 3/3: The front carbon carries ${item.f.join(', ')}; the back carbon carries ${item.b.join(', ')}.`)};$('#np-clear').onclick=()=>render();$('#np-previous').onclick=()=>{const total=active().length;index=(index+total-1)%total;render()};$('#np-next').onclick=()=>{const total=active().length;index=(index+1)%total;render()};$('#np-question').onchange=e=>{index=+e.target.value;render()};
for(const m of ['to','from'])$('#np-mode-'+m).onclick=()=>{mode=m;index=0;for(const x of ['to','from'])$('#np-mode-'+x).setAttribute('aria-pressed',String(x===m));fill()};for(const l of ['easy','moderate','hard'])$('#np-level-'+l).onclick=()=>{level=l;index=0;for(const x of ['easy','moderate','hard'])$('#np-level-'+x).setAttribute('aria-pressed',String(x===l));fill()};fill();
})();
