/* Small, dependency-free molecular sketcher. Answer chemistry lives in ProductChem. */
(()=>{'use strict';
const $=id=>document.getElementById(id),cp=ProductChem.copy;
class StructureEditor{
 constructor(onChange=()=>{}){this.board=$('p-board');this.onChange=onChange;this.graph={atoms:[],bonds:[]};this.tool='bond1';this.history=[];this.future=[];this.anchor=null;this.cursor={x:410,y:185};this.serial=0;this.locked=false;
 this.board.addEventListener('pointerdown',e=>this.down(e));this.board.addEventListener('pointermove',e=>this.motion(e));this.board.addEventListener('pointerup',e=>this.up(e));this.board.addEventListener('pointercancel',()=>{this.drag=null;$('p-preview').innerHTML='';});this.board.addEventListener('keydown',e=>this.keydown(e));
 document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>this.setTool(b.dataset.tool)));
 for(const[name,fn]of Object.entries({undo:()=>this.undo(),redo:()=>this.redo(),clear:()=>this.setGraph({atoms:[],bonds:[]}),tidy:()=>this.tidy(),fit:()=>this.fit()}))$('p-'+name).addEventListener('click',()=>{if(!this.locked)fn();});this.render();}
 getGraph(){return cp(this.graph);} snapshot(){this.history.push(this.getGraph());if(this.history.length>100)this.history.shift();this.future=[];}
 changed(){this.render();this.onChange(this.getGraph());} setGraph(g,record=true){if(record)this.snapshot();this.graph=cp(g);this.anchor=null;this.drag=null;if(!record){this.history=[];this.future=[];}this.changed();this.fit();}
 undo(){if(!this.history.length)return;this.future.push(this.getGraph());this.graph=this.history.pop();this.anchor=null;this.changed();} redo(){if(!this.future.length)return;this.history.push(this.getGraph());this.graph=this.future.pop();this.anchor=null;this.changed();}
 setTool(tool){if(this.locked)return;this.tool=tool;this.anchor=null;this.render();} setLocked(value){this.locked=value;document.querySelectorAll('[data-tool],.editor-actions button').forEach(b=>b.disabled=value);this.render();}
 atom(id){return this.graph.atoms.find(a=>a.id===id);} addAtom(p,element='C'){let id;do{id='draw'+(++this.serial);}while(this.atom(id));const a={id,element,charge:0,x:p.x,y:p.y};this.graph.atoms.push(a);return a;}
 addBond(a,b,order){if(a===b)return;const existing=this.graph.bonds.find(e=>ProductChem.key(e.a,e.b)===ProductChem.key(a,b));if(existing)existing.order=order;else this.graph.bonds.push({a,b,order});}
 point(e){const r=this.board.getBoundingClientRect(),v=this.board.getAttribute('viewBox').split(/\s+/).map(Number),scale=Math.min(r.width/v[2],r.height/v[3]);return{x:v[0]+(e.clientX-r.left-(r.width-v[2]*scale)/2)/scale,y:v[1]+(e.clientY-r.top-(r.height-v[3]*scale)/2)/scale};}
 target(e,p){if(e.target.dataset.atom)return{atom:e.target.dataset.atom};if(e.target.dataset.bond)return{bond:Number(e.target.dataset.bond)};const near=this.graph.atoms.filter(a=>!this.hidden?.has(a.id)).map(a=>({a,d:Math.hypot(a.x-p.x,a.y-p.y)})).sort((a,b)=>a.d-b.d)[0];return near?.d<18?{atom:near.a.id}:{};}
 snapped(a,p){let angle=Math.atan2(p.y-a.y,p.x-a.x);angle=Math.round(angle/(Math.PI/6))*Math.PI/6;const label=a.element==='C'?0:a.element==='Ph'?17:12,length=60+label;return{x:a.x+Math.cos(angle)*length,y:a.y+Math.sin(angle)*length};}
 activate(p,t={}){if(this.locked)return;const a=this.atom(t.atom);if(this.tool.startsWith('bond')){const order=Number(this.tool.slice(-1));if(t.bond!==undefined){this.snapshot();this.graph.bonds[t.bond].order=order;this.anchor=null;this.changed();return;}if(!this.anchor){if(a)this.anchor=a.id;else{this.snapshot();this.anchor=this.addAtom(p).id;this.changed();}this.render();return;}if(a?.id===this.anchor){this.anchor=null;this.render();return;}this.snapshot();const start=this.atom(this.anchor),end=a||this.addAtom(this.snapped(start,p));this.addBond(start.id,end.id,order);this.anchor=end.id;this.changed();return;}
 if(this.tool==='move'){this.anchor=a?.id||null;this.render();return;}
 if(this.tool==='erase'){if(!a&&t.bond===undefined)return;this.snapshot();if(a){this.graph.atoms=this.graph.atoms.filter(n=>n.id!==a.id);this.graph.bonds=this.graph.bonds.filter(b=>b.a!==a.id&&b.b!==a.id);}else this.graph.bonds.splice(t.bond,1);this.anchor=null;this.changed();return;}
 if(['positive','negative','neutral'].includes(this.tool)){if(!a)return;if(a.element==='Ph'&&this.tool!=='neutral'){$('p-atom-status').textContent='Place a formal charge on an atom; Ph represents a phenyl group.';return;}this.snapshot();a.charge=this.tool==='positive'?1:this.tool==='negative'?-1:0;this.changed();return;}
 this.snapshot();if(this.tool==='OMe'){const o=a||this.addAtom(p,'O');o.element='O';o.charge=0;const methyl=this.addAtom({x:o.x+72,y:o.y},'C');this.addBond(o.id,methyl.id,1);}else if(a){a.element=this.tool;a.charge=0;}else this.addAtom(p,this.tool);this.anchor=null;this.changed();}
 down(e){if(this.locked||e.button>0)return;e.preventDefault();const p=this.point(e),t=this.target(e,p);this.cursor=p;this.drag={p,t,id:e.pointerId,moved:false,before:this.getGraph(),shift:e.shiftKey};this.board.setPointerCapture?.(e.pointerId);}
 motion(e){if(!this.drag||e.pointerId!==this.drag.id)return;const p=this.point(e),d=this.drag;if(Math.hypot(p.x-d.p.x,p.y-d.p.y)<5&&!d.moved)return;d.moved=true;if(this.tool==='move'&&d.t.atom){const comp=ProductChem.components(d.before).find(c=>c.atoms.some(a=>a.id===d.t.atom)),ids=new Set(d.shift?comp.atoms.map(a=>a.id):[d.t.atom]);this.graph=cp(d.before);for(const a of this.graph.atoms)if(ids.has(a.id)){a.x+=p.x-d.p.x;a.y+=p.y-d.p.y;}this.render();}else if(this.tool.startsWith('bond')&&d.t.bond===undefined){const start=this.atom(d.t.atom)||d.p,end=this.target(e,p).atom?this.atom(this.target(e,p).atom):this.snapped(start,p);$('p-preview').innerHTML=`<line x1="${start.x}" y1="${start.y}" x2="${end.x}" y2="${end.y}" stroke="#44849b" stroke-width="2" stroke-dasharray="5 3"/>`;}}
 up(e){const d=this.drag;if(!d||d.id!==e.pointerId)return;const p=this.point(e),t=this.target(e,p);this.drag=null;$('p-preview').innerHTML='';if(d.moved&&this.tool==='move'&&d.t.atom){this.history.push(d.before);this.future=[];this.changed();}else if(d.moved&&this.tool.startsWith('bond')&&d.t.bond===undefined){this.snapshot();const start=this.atom(d.t.atom)||this.addAtom(d.p),end=this.atom(t.atom)||this.addAtom(this.snapped(start,p));this.addBond(start.id,end.id,Number(this.tool.slice(-1)));this.anchor=null;this.changed();}else this.activate(p,t);}
 keydown(e){if(this.locked)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?this.redo():this.undo();return;}if(e.key==='Escape'){this.anchor=null;this.render();return;}const shortcuts={c:'C',o:'O',n:'N',h:'H','1':'bond1','2':'bond2','3':'bond3','+':'positive','-':'negative','−':'negative',Delete:'erase',Backspace:'erase'};if(shortcuts[e.key]||shortcuts[e.key.toLowerCase()]){e.preventDefault();this.setTool(shortcuts[e.key]||shortcuts[e.key.toLowerCase()]);return;}if(e.key.startsWith('Arrow')){e.preventDefault();this.cursor.x+=e.key==='ArrowLeft'?-20:e.key==='ArrowRight'?20:0;this.cursor.y+=e.key==='ArrowUp'?-20:e.key==='ArrowDown'?20:0;this.render(true);}else if(e.key==='Enter'||e.key===' '){e.preventDefault();this.activate(this.cursor,e.target.dataset.atom?{atom:e.target.dataset.atom}:e.target.dataset.bond!==undefined?{bond:Number(e.target.dataset.bond)}:{});}}
 tidy(){if(!this.graph.atoms.length)return;this.snapshot();let offset=75;for(const comp of ProductChem.components(this.graph)){const used=new Set(),by=new Map(comp.atoms.map(a=>[a.id,a]));const root=comp.atoms.filter(a=>a.element==='C').sort((a,b)=>comp.bonds.filter(e=>e.a===b.id||e.b===b.id).length-comp.bonds.filter(e=>e.a===a.id||e.b===a.id).length)[0]||comp.atoms[0];root.x=offset;root.y=185;function visit(a,parent,angle){used.add(a.id);const next=comp.bonds.filter(b=>b.a===a.id||b.b===a.id).map(b=>by.get(b.a===a.id?b.b:b.a)).filter(n=>!used.has(n.id));next.forEach((n,i)=>{const linear=comp.bonds.filter(b=>b.a===a.id||b.b===a.id).some(b=>b.order===3)||comp.bonds.filter(b=>(b.a===a.id||b.b===a.id)&&b.order===2).length===2;const theta=parent?angle+(next.length===1?(linear?0:Math.sin(angle)>0?-Math.PI/3:Math.PI/3):next.length===3?[-Math.PI/2,0,Math.PI/2][i]:[-Math.PI/3,Math.PI/3][i]):(next.length===4?[-Math.PI/4,Math.PI/4,3*Math.PI/4,5*Math.PI/4]:[-Math.PI/6,Math.PI/2,7*Math.PI/6])[i];const len=60+(a.element==='C'?0:a.element==='Ph'?17:12)+(n.element==='C'?0:n.element==='Ph'?17:12);n.x=a.x+Math.cos(theta)*len;n.y=a.y+Math.sin(theta)*len;visit(n,a,theta);});}visit(root,null,0);const min=Math.min(...comp.atoms.map(a=>a.x)),max=Math.max(...comp.atoms.map(a=>a.x));for(const a of comp.atoms)a.x+=offset-min;offset+=max-min+140;}this.anchor=null;this.changed();this.fit();}
 fit(){const a=this.graph.atoms;if(!a.length){this.board.setAttribute('viewBox','0 0 820 370');return;}const b=this.layout.bounds,w=Math.max(820,b.w+100),h=Math.max(370,b.h+100);const x=b.x+b.w/2-w/2,y=b.y+b.h/2-h/2;this.board.setAttribute('viewBox',`${x} ${y} ${w} ${h}`);const background=$('p-grid-background');if(background)for(const[k,v]of Object.entries({x,y,width:w,height:h}))background.setAttribute(k,v);}
 render(cursor=false){const g=ProductChem.display(this.graph);this.hidden=new Set(g.atoms.filter(a=>a.hidden).map(a=>a.id));this.layout=layoutGraph(g,7,{compactOxygenBonds:true,tightPositiveOxygen:true,chargePairClearance:17,negativeChargeAbove:true,raisedNegativeCharges:true,cardinalPairs:true});$('p-molecules').innerHTML=additionMarkup(this.layout,{topic:'product'});let hits='';for(let i=0;i<this.graph.bonds.length;i++){const b=this.graph.bonds[i];if(this.hidden.has(b.a)||this.hidden.has(b.b))continue;const a=this.atom(b.a),n=this.atom(b.b);hits+=`<line class="editor-hit" data-bond="${i}" tabindex="0" role="button" aria-label="${b.order===1?'Single':b.order===2?'Double':'Triple'} bond" x1="${a.x}" y1="${a.y}" x2="${n.x}" y2="${n.y}" style="stroke-width:16"/>`;}for(const a of this.layout.atoms)hits+=`<circle class="editor-hit" data-atom="${a.id}" tabindex="0" role="button" aria-label="${a.element==='R'?'Phenyl':a.element}, formal charge ${a.charge||0}" cx="${a.x}" cy="${a.y}" r="19"/>`;$('p-hit').innerHTML=hits;const s=this.atom(this.anchor);$('p-selection').innerHTML=s?`<circle cx="${s.x}" cy="${s.y}" r="12" fill="none" stroke="#44849b" stroke-width="1.5"/>`:cursor?`<path d="M ${this.cursor.x-8} ${this.cursor.y} h16 M ${this.cursor.x} ${this.cursor.y-8} v16" stroke="#44849b"/>`:'';
 const comps=ProductChem.components(this.graph).filter(c=>c.atoms.some(a=>!this.hidden.has(a.id))).sort((a,b)=>Math.min(...a.atoms.map(n=>n.x))-Math.min(...b.atoms.map(n=>n.x)));for(let i=1;i<comps.length;i++){const left=Math.max(...comps[i-1].atoms.map(a=>a.x)),right=Math.min(...comps[i].atoms.map(a=>a.x));if(right-left>75)$('p-molecules').innerHTML+=`<text x="${(left+right)/2}" y="185" text-anchor="middle" font-family="Arial" font-size="24" fill="#172532">+</text>`;}
 $('p-empty').hidden=!!this.graph.atoms.length;const names={bond1:'Single bond',bond2:'Double bond',bond3:'Triple bond',positive:'Positive charge',negative:'Negative charge',neutral:'Remove charge',move:'Move',erase:'Eraser'};$('p-tool-status').textContent=(names[this.tool]||this.tool+' atom')+(this.anchor&&this.tool.startsWith('bond')?' · choose the next atom or point':'');$('p-components').textContent=comps.length+' product'+(comps.length===1?'':'s')+' drawn';$('p-atom-status').textContent=ProductChem.validation(this.graph);$('p-undo').disabled=this.locked||!this.history.length;$('p-redo').disabled=this.locked||!this.future.length;document.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===this.tool)));}
}
globalThis.StructureEditor=StructureEditor;
})();
