(()=>{'use strict';const $=id=>document.getElementById(id),names={addition:'Nucleophilic Addition',leaving:'Loss of Leaving Group',proton:'Proton Transfer',rearrangement:'Rearrangement'},drafts=new Map(),done=new Set();let level='easy',index=0,identified=false,loading=false,activeId=null;const questions=()=>PRODUCT_BANK.filter(q=>q.level===level),current=()=>questions()[index];const editor=new StructureEditor(()=>{if(!loading){save();tell('');}});
function tell(message,state=''){$('p-feedback').textContent=message;$('p-feedback').dataset.state=state;}
function save(){if(activeId)drafts.set(activeId,{graph:editor.getGraph(),identified});}
function progress(){$('p-score').textContent=`Completed: ${done.size} / ${PRODUCT_BANK.length}`;$('p-progress').style.width=100*questions().filter(q=>done.has(q.id)).length/questions().length+'%';}
function drawingStage(q){const ready=identified; $('p-editor-section').hidden=!ready;$('p-drawing-help').hidden=!ready;$('p-editor-gate').hidden=ready;editor.setLocked(!ready||done.has(q.id));$('p-board').setAttribute('aria-disabled',String(!ready||done.has(q.id)));$('p-board').setAttribute('tabindex',ready?'0':'-1');const equilibrium=q.topic==='proton';$('p-reaction-arrow').setAttribute('aria-label',equilibrium?'Equilibrium arrow':'Reaction arrow');$('p-reaction-arrow').innerHTML=equilibrium?'<path d="M 5 13 H 65 L 56 7 M 65 23 H 5 L 14 29" fill="none" stroke="#172532" stroke-width="1.8"/>':'<path d="M 5 18 H 65 M 56 12 L 65 18 L 56 24" fill="none" stroke="#172532" stroke-width="1.8"/>';}
function begin(n=0){save();index=n;const q=current(),draft=drafts.get(q.id);activeId=q.id;identified=!!draft?.identified;loading=true;editor.setLocked(false);editor.setGraph(draft?.graph||{atoms:[],bonds:[]},false);editor.setLocked(done.has(q.id));loading=false;$('p-prompt').innerHTML=globalThis.PRODUCT_PROMPTS?.[q.id]||mechanismPromptSVG(q);$('p-count').textContent=`Question ${index+1} of ${questions().length}`;$('p-title').textContent=`Question ${index+1}: Follow the arrows. Predict the product/s.`;$('p-question').value=index;$('p-prev').disabled=index===0;$('p-next').disabled=index===questions().length-1;drawingStage(q);$('p-check').disabled=!identified||done.has(q.id);$('p-mechanism-result').textContent=identified?'✓ '+names[q.topic]:'';$('p-type-feedback').textContent=identified?'Correct. Draw the product/s in the box beside the reaction.':'Choose the mechanism before drawing its product/s.';$('p-type-feedback').dataset.state=identified?'correct':'';document.querySelectorAll('[data-mechanism]').forEach(b=>{b.disabled=identified;b.classList.toggle('correct-choice',identified&&b.dataset.mechanism===q.topic);b.classList.remove('wrong-choice');});tell(done.has(q.id)?'Correct. '+q.explanation:'',done.has(q.id)?'correct':'');progress();}
function choose(next){save();activeId=null;level=next;index=0;loading=true;editor.setGraph({atoms:[],bonds:[]},false);loading=false;document.querySelectorAll('[data-product-level]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.productLevel===level)));$('p-question').innerHTML=questions().map((q,i)=>`<option value="${i}">Question ${i+1}</option>`).join('');begin(0);}
function identify(type){if(identified)return;const q=current();document.querySelectorAll('[data-mechanism]').forEach(b=>b.classList.remove('wrong-choice'));if(type!==q.topic){document.querySelector(`[data-mechanism="${type}"]`).classList.add('wrong-choice');$('p-type-feedback').textContent='Try again. Identify the elementary change shown by the arrows.';$('p-type-feedback').dataset.state='incorrect';return;}identified=true;save();drawingStage(q);$('p-check').disabled=false;$('p-type-feedback').textContent='Correct. Draw the product/s in the box beside the reaction.';$('p-type-feedback').dataset.state='correct';$('p-mechanism-result').textContent='✓ '+names[type];document.querySelectorAll('[data-mechanism]').forEach(b=>{b.disabled=true;b.classList.toggle('correct-choice',b.dataset.mechanism===type);});}
function check(){if(!identified||done.has(current().id))return;const result=ProductChem.check(current(),editor.getGraph());tell(result.message,result.correct?'correct':'incorrect');if(result.correct){done.add(current().id);drawingStage(current());$('p-check').disabled=true;save();progress();}return result;}
$('p-check').addEventListener('click',check);$('p-hint').addEventListener('click',()=>tell('Hint: '+current().hint));$('p-prev').addEventListener('click',()=>{if(index>0)begin(index-1);});$('p-next').addEventListener('click',()=>{if(index<questions().length-1)begin(index+1);});$('p-question').addEventListener('change',e=>begin(Number(e.target.value)));document.querySelectorAll('[data-product-level]').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.productLevel)));document.querySelectorAll('[data-mechanism]').forEach(b=>b.addEventListener('click',()=>identify(b.dataset.mechanism)));
// Initial entry must not create a draft for a question that has not been shown.
loading=true;choose('easy');loading=false;if(globalThis.__PRODUCT_TEST__)globalThis.productApi={editor,choose,begin,identify,check,current,getState:()=>({level,index,identified,done:[...done]})};
})();
